DROP TABLE IF EXISTS person_data CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS illness CASCADE;
DROP TABLE IF EXISTS medical_card CASCADE;
DROP TABLE IF EXISTS contact CASCADE;

DROP SEQUENCE IF EXISTS person_data_seq;
DROP SEQUENCE IF EXISTS address_seq;
DROP SEQUENCE IF EXISTS illness_seq;
DROP SEQUENCE IF EXISTS medical_card_seq;
DROP SEQUENCE IF EXISTS contact_seq;